packages:
  - 'examples/*'
  - 'packages/*'

catalog:
  '@types/node': '20.17.10'
  '@lynxtaa/eslint-config': '0.13.0'
  '@lynxtaa/prettier-config': '0.2.0'
  'eslint': '9.17.0'
  'jest': '29.7.0'
  'jest-environment-jsdom': '29.7.0'
  'prettier': '3.4.2'
  'typescript': '5.7.2'
